# Generated by Django 3.2.8 on 2021-10-27 18:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HospitalCity', to='covid.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LaboratoryCity', to='covid.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('gender', models.PositiveSmallIntegerField(choices=[(2, 'K'), (1, 'M'), (3, 'other')])),
                ('age', models.PositiveSmallIntegerField()),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('date_of_received_information', models.DateField(blank=True, null=True)),
                ('date_of_positive_result', models.DateField(auto_now_add=True)),
                ('source_of_infection', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PersonCity', to='covid.cities')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital', to='covid.hospitals')),
                ('laboratory_performing_tests', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='covid.laboratories')),
                ('whereabouts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whereabouts', to='covid.cities')),
            ],
        ),
    ]
