# Generated by Django 3.2.8 on 2021-10-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='address',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='cities',
            old_name='city',
            new_name='province',
        ),
        migrations.AlterField(
            model_name='persons',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'M'), (3, 'other'), (2, 'K')]),
        ),
    ]
