# Generated by Django 3.2.8 on 2021-10-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20211027_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='country',
            new_name='county',
        ),
        migrations.AlterField(
            model_name='persons',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(2, 'K'), (1, 'M'), (3, 'other')]),
        ),
    ]
