# Generated by Django 3.2.8 on 2021-10-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20211027_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratories',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persons',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(3, 'other'), (1, 'M'), (2, 'K')]),
        ),
    ]
