# Generated by Django 3.2.8 on 2021-10-27 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20211027_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city', to='covid.cities'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(3, 'other'), (1, 'M'), (2, 'K')]),
        ),
    ]
