# Generated by Django 3.2.8 on 2021-10-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20211027_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PersonCity', to='covid.cities'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'M'), (2, 'K'), (3, 'other')]),
        ),
    ]
