# Generated by Django 3.2.8 on 2021-10-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_auto_20211027_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='date_of_positive_result',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'M'), (2, 'K'), (3, 'other')]),
        ),
    ]
