# Generated by Django 3.2.8 on 2021-10-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0009_auto_20211027_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='hospitalization',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tal'), (0, 'Nie')], default=0),
        ),
        migrations.AddField(
            model_name='persons',
            name='quarantine',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tal'), (0, 'Nie')], default=0),
        ),
        migrations.AddField(
            model_name='persons',
            name='supervision',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tal'), (0, 'Nie')], default=0),
        ),
        migrations.AlterField(
            model_name='persons',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(2, 'K'), (1, 'M'), (3, 'other')]),
        ),
    ]
