# Generated by Django 3.2.8 on 2021-10-27 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0010_auto_20211027_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'M'), (2, 'K'), (3, 'other')]),
        ),
        migrations.AlterField(
            model_name='persons',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital', to='covid.hospitals'),
        ),
    ]
