# Generated by Django 3.2.8 on 2021-11-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0013_auto_20211028_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='Sportowa 13', max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'M'), (3, 'other'), (2, 'K')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='hospitalization',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tak'), (0, 'Nie')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='quarantine',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tak'), (0, 'Nie')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='supervision',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tak'), (0, 'Nie')], default=0),
        ),
    ]
